<?php
session_start();
if(!isset($_SESSION["email"]))
{
	header("Location:login.php");
	die();
}
else
{
	unset($_SESSION["email"]);
    unset($_SESSION["email"]);
    session_destroy();
	header("Location:login.php");
	die();
}
?>